  
version: "3.8"
services:
    api:
        # image: thomas-oliver/nestjs-dockerized 
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgresql
        environment: 
            NODE_ENV: development
        ports:
            - "5000:5000"
    postgresql:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment: 
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=tasks
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
