  
version: "3.8"
services:
    api:
        # image: thomas-oliver/nestjs-dockerized 
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://user:password@postgres:5432/tasks
            NODE_ENV: development
            
        ports:
            - "5000:5000"

    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test_db
         volumes:
            - ./data/postgres:/var/lib/postgresql/data
